const INTERVIEW_STATUS = {
    PENDING: null, SCHEDULED: null, INFORMED: null, CONFIRMED: null,
    ARRIVED: null, MISSED: null, MAYBE: null, REJECTED: null, ACCEPTED: null
};

Object.keys(INTERVIEW_STATUS).forEach(status => INTERVIEW_STATUS[status] = status);


export const TERMINAL_INTERVIEW_STATUS = [INTERVIEW_STATUS.REJECTED, INTERVIEW_STATUS.ACCEPTED];
export const DAY_TERMINAL_INTERVIEW_STATUS = [INTERVIEW_STATUS.MAYBE].concat(TERMINAL_INTERVIEW_STATUS);